import { Template } from "@/lib/types";

export const mockTemplates: Template[] = [
  // 5 Marketing templates
  {
    id: "template_001",
    name: "diwali_flash_sale_announcement",
    displayName: "Diwali Flash Sale Offer",
    category: "marketing",
    language: "en_US",
    status: "approved",
    header: {
      type: "image",
      mediaUrl:
        "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop&q=80",
    },
    body: {
      text: "Hello {{1}}, Diwali just got brighter! Get flat {{2}}% off across all subscriptions today with code {{3}}. Offer ends midnight!",
      variables: ["name", "discount_percentage", "coupon_code"],
      examples: ["Rajesh", "30", "DIWALI30"],
    },
    footer: { text: "Reply STOP to opt out" },
    buttons: [
      { type: "url", text: "Shop Deal", url: "https://mindclub.org/offers" },
      { type: "quick_reply", text: "Remind me later" },
    ],
    qualityScore: "green",
    usageCount: 4850,
    lastUsedAt: "2026-09-25T14:30:00Z",
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-09-10T12:00:00Z",
  },
  {
    id: "template_002",
    name: "exclusive_vip_product_preview",
    displayName: "VIP Product Exclusive Preview",
    category: "marketing",
    language: "en_US",
    status: "approved",
    header: {
      type: "text",
      text: "Exclusive Early Access for VIPs",
    },
    body: {
      text: "Hi {{1}}, as one of our most valued partners at {{2}}, we are thrilled to grant you early beta access to {{3}}.",
      variables: ["name", "company", "feature_name"],
      examples: ["Priyanka", "CloudScale", "Omnichannel AI Copilot"],
    },
    footer: { text: "MindClub Enterprise" },
    buttons: [{ type: "url", text: "Claim Access", url: "https://mindclub.org/vip-access" }],
    qualityScore: "green",
    usageCount: 1200,
    lastUsedAt: "2026-09-26T09:15:00Z",
    createdAt: "2026-08-15T11:00:00Z",
    updatedAt: "2026-09-01T15:00:00Z",
  },
  {
    id: "template_003",
    name: "festival_fest_hindi_offer",
    displayName: "त्योहार विशेष छूट संदेश",
    category: "marketing",
    language: "hi",
    status: "approved",
    header: {
      type: "text",
      text: "शुभ दीपावली विशेष ऑफर",
    },
    body: {
      text: "नमस्ते {{1}}, इस त्योहार के शुभ अवसर पर पाइए हमारे सभी प्लान्स पर {{2}}% की भारी छूट। सीमित समय के लिए उपलब्ध!",
      variables: ["name", "discount"],
      examples: ["रोहन", "25"],
    },
    footer: { text: "माइंडक्लब टीम" },
    buttons: [
      { type: "url", text: "ऑफर देखें", url: "https://mindclub.org/hi/offers" },
      { type: "phone", text: "कॉल करें", phoneNumber: "+918001234567" },
    ],
    qualityScore: "green",
    usageCount: 3200,
    lastUsedAt: "2026-09-24T18:00:00Z",
    createdAt: "2026-08-20T08:00:00Z",
    updatedAt: "2026-09-12T11:00:00Z",
  },
  {
    id: "template_004",
    name: "quarterly_enterprise_upgrade",
    displayName: "Quarterly Enterprise Upgrade",
    category: "marketing",
    language: "en_US",
    status: "pending",
    header: {
      type: "none",
    },
    body: {
      text: "Dear {{1}}, upgrade your team to Enterprise before {{2}} and unlock unlimited WhatsApp broadcast quotas and 24/7 dedicated engineering support.",
      variables: ["contact_name", "valid_date"],
      examples: ["Amit", "Sept 30"],
    },
    footer: { text: "MindClub Growth Team" },
    buttons: [{ type: "quick_reply", text: "Schedule Consultation" }],
    qualityScore: "unknown",
    usageCount: 0,
    createdAt: "2026-09-26T12:00:00Z",
    updatedAt: "2026-09-26T12:00:00Z",
  },
  {
    id: "template_005",
    name: "winback_churned_leads_promo",
    displayName: "We Miss You Winback Offer",
    category: "marketing",
    language: "en_US",
    status: "rejected",
    rejectionReason:
      "Content flagged for aggressive promotional wording. Please adjust body text and opt-out clarity.",
    header: {
      type: "text",
      text: "Come Back and Save Big",
    },
    body: {
      text: "Hey {{1}}! We miss having {{2}} with us. Reactivate your CRM suite today and take 50% off for 6 months!",
      variables: ["name", "company"],
      examples: ["Karthik", "QuickLogistics"],
    },
    footer: { text: "Reply STOP to stop" },
    buttons: [{ type: "url", text: "Reactivate Account", url: "https://mindclub.org/reactivate" }],
    qualityScore: "red",
    usageCount: 0,
    createdAt: "2026-09-15T09:00:00Z",
    updatedAt: "2026-09-16T14:00:00Z",
  },

  // 5 Utility templates
  {
    id: "template_006",
    name: "order_confirmation_dispatch",
    displayName: "Order Dispatch Notification",
    category: "utility",
    language: "en_US",
    status: "approved",
    header: {
      type: "text",
      text: "Order Dispatched #{{1}}",
      variables: ["order_id"],
    },
    body: {
      text: "Hello {{1}}, your order {{2}} has been shipped via {{3}}. Tracking Number: {{4}}. Expected delivery: {{5}}.",
      variables: ["customer_name", "order_id", "courier", "tracking_no", "eta"],
      examples: ["Rajesh", "ORD-9821", "BlueDart", "BD8892182", "30th Sep"],
    },
    footer: { text: "Thank you for shopping with us" },
    buttons: [
      { type: "url", text: "Track Package", url: "https://track.bluedart.com/{{1}}" },
      { type: "quick_reply", text: "Help with Order" },
    ],
    qualityScore: "green",
    usageCount: 4210,
    lastUsedAt: "2026-09-28T07:15:00Z",
    createdAt: "2026-07-10T08:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "template_007",
    name: "appointment_reminder_schedule",
    displayName: "Appointment Reminder Schedule",
    category: "utility",
    language: "en_US",
    status: "approved",
    header: {
      type: "none",
    },
    body: {
      text: "Hello {{1}}, reminder that your appointment with {{2}} is confirmed for {{3}} at {{4}}. Please arrive 10 minutes prior.",
      variables: ["patient_name", "doctor_name", "date", "time"],
      examples: ["Divya", "Dr. Mehta", "29 Sep", "10:30 AM"],
    },
    footer: { text: "Reply 1 to Confirm or 2 to Reschedule" },
    buttons: [
      { type: "quick_reply", text: "Confirm Attendance" },
      { type: "quick_reply", text: "Reschedule" },
    ],
    qualityScore: "green",
    usageCount: 2940,
    lastUsedAt: "2026-09-27T16:00:00Z",
    createdAt: "2026-07-20T09:30:00Z",
    updatedAt: "2026-08-05T12:00:00Z",
  },
  {
    id: "template_008",
    name: "invoice_payment_receipt",
    displayName: "Payment Receipt & Tax Invoice",
    category: "utility",
    language: "en_US",
    status: "approved",
    header: {
      type: "text",
      text: "Payment Receipt Confirmed",
    },
    body: {
      text: "Dear {{1}}, we have received your payment of ₹{{2}} for invoice {{3}}. Transaction ID: {{4}}.",
      variables: ["name", "amount", "invoice_no", "txn_id"],
      examples: ["Amit", "14,999", "INV-2026-089", "TXN9812739"],
    },
    footer: { text: "MindClub Billing" },
    buttons: [
      { type: "url", text: "Download PDF Invoice", url: "https://mindclub.org/inv/pdf/{{1}}" },
    ],
    qualityScore: "green",
    usageCount: 1850,
    lastUsedAt: "2026-09-28T06:45:00Z",
    createdAt: "2026-07-25T11:00:00Z",
    updatedAt: "2026-08-10T14:00:00Z",
  },
  {
    id: "template_009",
    name: "service_ticket_resolution_hindi",
    displayName: "सेवा टिकट समाधान सूचना",
    category: "utility",
    language: "hi",
    status: "approved",
    header: {
      type: "none",
    },
    body: {
      text: "नमस्ते {{1}}, आपका सहायता टिकट #{{2}} सफलतापूर्वक हल कर दिया गया है। विवरण: {{3}}। यदि आपके पास और प्रश्न हैं, तो कृपया उत्तर दें।",
      variables: ["name", "ticket_id", "summary"],
      examples: ["सुनीता", "TKT-441", "खाता सत्यापन पूर्ण"],
    },
    footer: { text: "माइंडक्लब ग्राहक सेवा" },
    buttons: [
      { type: "quick_reply", text: "संतुष्ट हूँ" },
      { type: "quick_reply", text: "पुनः खोलें" },
    ],
    qualityScore: "green",
    usageCount: 940,
    lastUsedAt: "2026-09-25T11:00:00Z",
    createdAt: "2026-08-10T07:00:00Z",
    updatedAt: "2026-08-25T09:00:00Z",
  },
  {
    id: "template_010",
    name: "subscription_expiry_alert",
    displayName: "Subscription Expiration Alert",
    category: "utility",
    language: "en_US",
    status: "pending",
    header: {
      type: "text",
      text: "Action Required: Renewal Due",
    },
    body: {
      text: "Hi {{1}}, your {{2}} plan will expire on {{3}}. Auto-renew now to prevent webhook suspension.",
      variables: ["name", "plan", "expiry_date"],
      examples: ["Kunal", "Pro Annual", "30 Oct 2026"],
    },
    footer: { text: "Auto-debit active" },
    buttons: [{ type: "url", text: "Renew Now", url: "https://mindclub.org/renew" }],
    qualityScore: "unknown",
    usageCount: 0,
    createdAt: "2026-09-27T08:00:00Z",
    updatedAt: "2026-09-27T08:00:00Z",
  },

  // 2 Authentication templates
  {
    id: "template_011",
    name: "secure_login_otp_verification",
    displayName: "Secure Login OTP Verification",
    category: "authentication",
    language: "en_US",
    status: "approved",
    body: {
      text: "{{1}} is your MindClub verification code. For your security, never share this OTP with anyone.",
      variables: ["otp_code"],
      examples: ["482910"],
    },
    footer: { text: "Code expires in 5 minutes" },
    buttons: [{ type: "copy_code", text: "Copy Code", example: "482910" }],
    qualityScore: "green",
    usageCount: 4950,
    lastUsedAt: "2026-09-28T07:20:00Z",
    createdAt: "2026-07-01T06:00:00Z",
    updatedAt: "2026-07-15T08:00:00Z",
  },
  {
    id: "template_012",
    name: "password_reset_one_time_token",
    displayName: "Password Reset Token",
    category: "authentication",
    language: "en_US",
    status: "draft",
    body: {
      text: "Use code {{1}} to reset your account password. If you did not make this request, please contact support immediately.",
      variables: ["reset_code"],
      examples: ["918234"],
    },
    footer: { text: "MindClub Security" },
    buttons: [{ type: "copy_code", text: "Copy Code", example: "918234" }],
    qualityScore: "unknown",
    usageCount: 0,
    createdAt: "2026-09-28T05:00:00Z",
    updatedAt: "2026-09-28T05:00:00Z",
  },
];
